language: c
sudo: false
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
env:
  - global:
    - TRAVIS=true
    - R_LIBS_USER=~/.R/library
cache:
  directories:
    $R_LIBS_USER
before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (!require("devtools")) install.packages("devtools", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("plyr")) install.packages("plyr", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("pryr")) install.packages("pryr", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("XML")) install.packages("XML", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("httr")) install.packages("httr", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("yaml")) install.packages("yaml", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("digest")) install.packages("digest", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("crayon")) install.packages("crayon", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("roxygen2")) install.packages("roxygen2", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("testthat")) install.packages("testthat", repos = "http://cran.rstudio.com/")'
script: "Rscript -e 'quit(save = "no", status = if (sum(as.data.frame(devtools::test())$failed) == 0) { 0 } else { 1 }, runLast = FALSE)'"
after_success:
  - Rscript -e 'library(covr);coveralls()'
notifications:
  email:
    on_success: change
    on_failure: change
